[project]
name = "offers-reranker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1,<0.28.2",
    "logfire>=4.14.2,<4.15.0",
    "python-dotenv>=1.2.1",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.mypy]
python_version = "3.12"
strict = true
warn_redundant_casts = true
warn_unreachable = true

plugins = ["pydantic.mypy"]

mypy_path = "."
explicit_package_bases = true

[tool.pydantic.mypy]
init_forbid_extra = true
init_typed = true
