name: ETL CI

on:
  pull_request:
    paths:
      - 'etl/**'
      - '.github/workflows/etl-ci.yaml'
      - '.github/workflows/reusable-ci.yaml'

jobs:
  etl-ci:
    name: Code, Typing & Linting
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      working-directory: ./etl
      python-version: '3.12'
      run-tests: false
      run-mypy: true
      run-ruff: true

