name: Inference CI

on:
  pull_request:
    paths:
      - 'inference/**'
      - '.github/workflows/torchseve-ci.yaml'
      - '.github/workflows/reusable-ci.yaml'

jobs:
  inference-ci:
    name: Inference CI
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      working-directory: ./inference-torchserve
      python-version: '3.12'
      run-tests: true
      run-mypy: true
      run-ruff: true

